version: "3.7"
services:
 #Contenedor de la API
  app:
  #La aplicaci칩n depender치 del contenedor de la base de datos
    depends_on:
      - "mysql"
    container_name: flask-app
    build:
      context: ./app
      dockerfile: Dockerfile
    #Colocar nombre a la imagen
    image: flask-app:lastest
    #Crear variables de entorno
    environment:
      FLASK_ENV: development
      DB_USUARIO: root
      DB_CLAVE: nllitc129404
      DB_HOST: mysql
      DB_NOMBRE: db_api_python
      JWT_SECRET_KEY: esta-es-mi-clave-secreta
    #Crear puerto donde correr치 la aplicaci칩n
    ports:
      - "5000:5000"
    restart: always
    networks:
      - internal

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=esta-es-mi-clave-secreta
      - MYSQL_DATABASE=db_api_python
    ports:
      - "3306:3306"
    networks:
      - internal

networks:
  internal:
    driver: bridge
